{% set name = "fiftyone" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fiftyone-{{ version }}.tar.gz
  sha256: 9f61aabff71606cfc0b224465f0fea0cac1b2bf64895948bfa40c8c4c928da4a
  patches:
    # Fiftyone by default ships with their own mongodb (fiftyone-db) to store dataset data
    - 0000-dropin-fiftyone-db.patch

build:
  noarch: python
  entry_points:
    - fiftyone=fiftyone.core.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - importlib-metadata
    - setuptools
    - wheel
    - pip
    - fiftyone-brain >=0.17.0,<0.18
  run:
    - python >=3.6
    - aiofiles
    - argcomplete
    - beautifulsoup4
    - boto3
    - cachetools
    - dacite >=1.6.0,<1.8.0
    - deprecated
    - ftfy
    - humanize
    - hypercorn >=0.13.2
    - importlib-metadata
    - jinja2 ==3.0.3
    - python-kaleido !=0.2.1.post1
    - matplotlib-base
    - mongoengine # ==0.24.2
    - motor >=2.5
    - numpy
    - packaging
    - pandas
    - pillow >=6.2
    - plotly >=4.14
    - pprintpp
    - psutil
    - pydash
    - pymongo >=3.12,<4.9
    - pytz
    - pyyaml
    - regex
    - retrying
    - scikit-learn
    - scikit-image
    - scipy
    - setuptools
    - sseclient-py >=1.7.2,<2
    - sse-starlette >=0.10.3,<1
    - starlette >=0.24.0
    - strawberry-graphql
    - tabulate
    - xmltodict
    - universal-analytics-python3 >=1.0.1,<2
    - fiftyone-brain >=0.17.0,<0.18
    - mongodb >=4.4 # https://docs.voxel51.com/user_guide/config.html#using-a-different-mongodb-version
    - voxel51-eta >=0.12.7,<0.13
    - opencv

test:
  imports:
    - fiftyone
    - fiftyone.brain
  commands:
    - pip check
    - fiftyone --help
  requires:
    - pip

about:
  home: https://github.com/voxel51/fiftyone
  summary: 'FiftyOne: the open-source tool for building high-quality datasets and computer vision models'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucasew
